# Generated by Django 4.2.7 on 2024-02-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_token',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='verify_token'),
        ),
    ]
