# Generated by Django 5.0.1 on 2024-01-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_message', models.CharField(max_length=150, verbose_name='theme_message')),
                ('text_message', models.TextField(verbose_name='text_message')),
                ('time_send', models.CharField(max_length=10, verbose_name='time_send')),
                ('periodicity', models.CharField(choices=[('Once a day', 'Once a day'), ('Once a week', 'Once a week'), ('Once a month', 'Once a month')], default='Once a day', verbose_name='periodicity')),
                ('status', models.CharField(blank=True, null=True, verbose_name='status')),
                ('clients', models.ManyToManyField(to='client.client', verbose_name='clients')),
            ],
            options={
                'verbose_name': 'newsletter',
                'verbose_name_plural': 'newsletters',
            },
        ),
    ]
