# Generated by Django 5.0.1 on 2024-01-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Launched', 'Launched'), ('Finished', 'Finished')], default='Created', verbose_name='status'),
        ),
    ]
