# Generated by Django 5.0.1 on 2024-01-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_alter_newsletter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='time_send',
            field=models.DateTimeField(max_length=10, verbose_name='time_send'),
        ),
    ]
