# Generated by Django 5.0.1 on 2024-01-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_alter_newsletter_time_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='time_stop',
            field=models.CharField(default='00:00', max_length=5, verbose_name='time_stop (in format HH:MM)'),
        ),
    ]
