# Generated by Django 5.0.1 on 2024-01-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0005_newsletter_time_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='test',
            field=models.CharField(blank=True, null=True, verbose_name='test'),
        ),
    ]
