# Generated by Django 5.0.1 on 2024-01-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0006_newsletter_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='test',
        ),
    ]
