# Generated by Django 4.2.7 on 2024-02-04 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0009_alter_newsletter_time_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='time_send',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='time_stop',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='next_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='next_date'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start_date'),
        ),
    ]
