# Generated by Django 4.2.7 on 2024-02-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0011_remove_newsletter_next_date_newsletter_stop_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='next_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='next_date'),
        ),
    ]
