# Generated by Django 4.2.7 on 2024-02-04 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0012_newsletter_next_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='next_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='next_date'),
        ),
    ]
