# Generated by Django 5.0.1 on 2024-01-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_date', models.DateTimeField(verbose_name='try_date')),
                ('try_status', models.CharField(verbose_name='try_status')),
                ('try_response', models.CharField(verbose_name='tru_status')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
            },
        ),
    ]
