# Generated by Django 5.0.1 on 2024-01-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_email'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='clients',
            field=models.ManyToManyField(to='client.client', verbose_name='clients'),
        ),
    ]
