# Generated by Django 5.0.1 on 2024-01-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_log_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='clients',
        ),
        migrations.AddField(
            model_name='log',
            name='clients',
            field=models.CharField(blank=True, null=True, verbose_name='clients'),
        ),
    ]
