# Generated by Django 5.0.1 on 2024-01-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_alter_log_try_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='email',
            field=models.CharField(blank=True, null=True, verbose_name='email'),
        ),
    ]
