# Generated by Django 5.0.1 on 2024-01-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_alter_log_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='try_response',
            field=models.CharField(verbose_name='try_status'),
        ),
    ]
