# Generated by Django 4.2.7 on 2024-02-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_alter_log_try_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='try_date',
            field=models.DateTimeField(verbose_name='try_date'),
        ),
    ]
